const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),out=process.env.TEST_OUTPUT||path.join(root,'test-results');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'],env:process.env});const context=await browser.newContext({viewport:{width:1360,height:900},locale:'ja-JP'});const page=await context.newPage(),errors=[],external=[];page.on('pageerror',e=>{errors.push(e.message);console.log('PAGEERROR',e.message)});page.on('request',r=>{if(/^https?:/.test(r.url()))external.push(r.url())});const url='file://'+root+'/dist/index.html';await page.goto(url);await page.waitForFunction(()=>document.querySelector('#heroSampleButton')?.textContent.includes('サンプル'));console.log('loaded');await page.locator('#heroSampleButton').click();await page.waitForSelector('#reviewPage.is-current');assert.equal(await page.locator('#recordPage').isVisible(),false);await page.locator('#playbackSeek').fill('250');await page.locator('#noteText').fill('腰を落とす位置を確認。<script>not code</script>');await page.locator('#addNoteButton').click();await page.waitForFunction(()=>document.querySelectorAll('.moment').length===1);await page.locator('#playbackSeek').fill('600');await page.locator('#noteText').fill('立ち上がりの姿勢を見返す');await page.locator('#addNoteButton').click();await page.waitForFunction(()=>document.querySelectorAll('.moment').length===2);await page.locator('#exportFilename').fill('練習ノート-01');await page.locator('#languageButton').click();assert.equal(await page.locator('#exportFilename').inputValue(),'練習ノート-01');await page.locator('#languageButton').click();
async function download(id,ext){const pending=page.waitForEvent('download');await page.locator(id).click();const d=await pending;assert.equal(d.suggestedFilename(),'練習ノート-01'+ext);const dest=path.join(out,'export'+ext);await d.saveAs(dest);return dest}
console.log('notes-created');const jsonFile=await download('#exportJsonButton','.pose.json');const rec=JSON.parse(fs.readFileSync(jsonFile));assert.equal(rec.notes.length,2);assert.equal(rec.samples.length,76);const htmlFile=await download('#exportHtmlButton','.html');await download('#exportCsvButton','.csv');const png=await download('#exportSheetButton','.png');assert.equal(fs.readFileSync(png).subarray(1,4).toString(),'PNG');
console.log('exports-saved');await page.locator('[data-note-delete]').first().click();await page.waitForFunction(()=>document.querySelectorAll('.moment').length===1);await page.locator('#appToastAction').click();await page.waitForFunction(()=>document.querySelectorAll('.moment').length===2);console.log('undo-done');await page.reload();await page.locator('.desktop-tab[data-page="reviewPage"]').click();assert.equal(await page.locator('.moment').count(),2);await page.locator('.moment-open').last().click();assert.equal(await page.locator('#playbackSeek').inputValue(),'600');
console.log('reload-done');
// Failed imports must leave the valid current notebook intact.
await page.locator('#importFileInput').setInputFiles({name:'invalid.pose.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({...rec,samples:[{t:0,landmarks:[]}]}))});await page.waitForFunction(()=>document.querySelector('#appToastMessage').textContent==='対応していないPoseデータです');assert.equal(await page.locator('.moment').count(),2);
await page.locator('[data-note-edit]').first().click();await page.locator('#editNoteText').fill('腰を落とす位置を確認。');await page.locator('#saveNoteEdit').click();await page.waitForSelector('#editNoteDialog',{state:'hidden'});await page.locator('#appToast').evaluate(e=>e.classList.remove('show'));await page.screenshot({animations:'disabled',path:path.join(root,'assets/screenshot.png')});await page.locator('#languageButton').click();await page.screenshot({animations:'disabled',path:path.join(root,'assets/screenshot-en.png')});
// Legacy reference import/export and advanced tools remain functional.
await page.locator('[data-go-page="referencePage"]').first().click();await page.locator('#referenceNameInput').fill('Baseline');await page.locator('#saveReferenceButton').click();await page.waitForFunction(()=>document.querySelectorAll('#referenceList .library-item').length===1);await page.locator('.desktop-tab[data-page="libraryPage"]').click();await page.locator('#addSampleButton').click();await page.locator('.desktop-tab[data-page="reviewPage"]').click();await page.locator('[data-go-page="comparePage"]').first().click();const vals=await page.locator('#compareSelectA option').evaluateAll(nodes=>nodes.map(n=>n.value).filter(Boolean));await page.locator('#compareSelectA').selectOption(vals[0]);await page.locator('#compareSelectB').selectOption(vals[1]);await page.locator('#runCompareButton').click();await page.waitForSelector('#compareContent:not([hidden])');await page.locator('.desktop-tab[data-page="reviewPage"]').click();await page.locator('[data-go-page="analyzePage"]').first().click();assert.notEqual(await page.locator('#metricCurrent').textContent(),'—');
await page.setViewportSize({width:360,height:800});for(const id of ['recordPage','reviewPage','libraryPage']){await page.locator(`[data-mobile-page-target="${id}"]`).click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,id)}await page.locator('[data-mobile-page-target="reviewPage"]').click();await page.locator('#languageButton').click();await page.locator('[data-mobile-page-target="libraryPage"]').click();await page.locator('[data-select-recording]').last().click();await page.locator('#appToast').evaluate(e=>e.classList.remove('show'));await page.screenshot({animations:'disabled',path:path.join(root,'assets/screenshot-mobile.png'),fullPage:true});await page.setViewportSize({width:360,height:420});await page.locator('#helpButton').click();const help=await page.locator('#helpDialog').boundingBox();assert.ok(help.y>=0&&help.y+help.height<=420);await page.locator('#helpDialog .dialog-body').evaluate(e=>e.scrollTop=e.scrollHeight);assert.ok(await page.locator('#helpDialog .dialog-body [data-close-dialog]').isVisible());await page.keyboard.press('Escape');assert.equal(await page.locator('#helpDialog').isVisible(),false);
const viewer=await context.newPage();viewer.on('pageerror',e=>errors.push('viewer:'+e.message));await viewer.goto('file://'+htmlFile);assert.equal(await viewer.locator('#viewerNotes button').count(),2);await viewer.locator('#viewerNotes button').last().click();assert.equal(await viewer.locator('#seek').inputValue(),'600');assert.equal(await viewer.locator('#viewerNotes script').count(),0);await viewer.close();
const compact=await context.newPage();compact.on('pageerror',e=>errors.push('compact:'+e.message));await compact.goto('file://'+root+'/dist/index.self-extract.html');await compact.waitForSelector('#heroSampleButton',{timeout:20000});await compact.locator('#heroSampleButton').click();await compact.waitForSelector('#reviewPage.is-current');await compact.close();
// Delete every recording; exports must become unavailable.
await page.setViewportSize({width:1360,height:900});await page.locator('.desktop-tab[data-page="reviewPage"]').click();
while(await page.locator('#recordingList .library-item').count()){await page.locator('#deleteRecordingButton').click();await page.locator('#appConfirmOk').click();await page.waitForSelector('#appConfirmDialog',{state:'hidden'});await page.waitForTimeout(50)}
for(const id of ['exportJsonButton','exportCsvButton','exportHtmlButton','exportSheetButton'])assert.equal(await page.locator('#'+id).isDisabled(),true);
assert.deepEqual(errors,[]);assert.deepEqual(external,[]);console.log(JSON.stringify({passed:true,checks:['capture/review/library','notes create/jump/delete/undo/reload','filename language preservation','JSON/CSV/HTML/PNG actual exports','malformed import isolation','reference save','comparison','joint analysis','360px overflow','short help dialog','viewer notes with safe text','self-extract file','no external requests','no page errors']},null,2));await browser.close()})().catch(e=>{console.error(e);process.exit(1)});
