const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(__dirname+'/../src/index.template.html','utf8');
function fn(name){const start=source.indexOf('function '+name+'(');assert.ok(start>=0,`${name} exists`);let p=source.indexOf('{',start),n=1,i=p+1;for(;i<source.length&&n;i++){if(source[i]==='{')n++;if(source[i]==='}')n--;}return source.slice(start,i)}
function engine(){const c={Number,Array,Math,Set};vm.createContext(c);vm.runInContext(['clamp','validSamples','interpolateLandmarks','sampleAt','validatePoseObject'].map(fn).join('\n')+';this.api={sampleAt,validatePoseObject}',c);return c.api}
const point=()=>({x:.5,y:.5,z:0,visibility:.9}),sample=t=>({t,landmarks:Array.from({length:33},point)}),record=()=>({format:'browser-kitty-pose',schemaVersion:1,kind:'recording',duration:1000,samples:[sample(0),sample(100),sample(1000)]});
test('legacy recording accepted',()=>assert.equal(engine().validatePoseObject(record()),true));
test('rejects poisoned coordinates and nonmonotonic time',()=>{for(const mutate of [r=>r.samples[0].landmarks[2].x=Infinity,r=>r.samples[1].t=-1,r=>r.duration=Infinity,r=>r.samples=[]]){const r=record();mutate(r);assert.equal(engine().validatePoseObject(r),false)}});
test('missing detection remains blank',()=>{const r=record();r.samples.splice(2,0,{t:200,landmarks:null});assert.equal(engine().sampleAt(r,500),null)});
test('large unobserved interval remains blank',()=>assert.equal(engine().sampleAt(record(),600),null));
test('notes reject invalid timestamps and preserve valid optional legacy extension',()=>{const r=record();r.notes=[{id:'n',t:200,text:'Look here'}];assert.equal(engine().validatePoseObject(r),true);r.notes[0].t=2000;assert.equal(engine().validatePoseObject(r),false)});
test('legacy motion/pose references roundtrip',()=>{const r=record(),reference={format:r.format,schemaVersion:1,kind:'reference',type:'motion',regions:['knees'],data:r};assert.equal(engine().validatePoseObject(reference),true);reference.type='pose';reference.data={...r,duration:0,samples:[sample(0)],notes:[]};assert.equal(engine().validatePoseObject(reference),true)});
test('duplicate notes, oversized sequences, invalid dimensions are rejected',()=>{const r=record();r.notes=[{id:'n',t:0,text:'a'},{id:'n',t:1,text:'b'}];assert.equal(engine().validatePoseObject(r),false);delete r.notes;r.meta={aspectRatio:0};assert.equal(engine().validatePoseObject(r),false);delete r.meta;r.samples=Array(20001).fill(sample(0));assert.equal(engine().validatePoseObject(r),false)});
test('reference notes must be text',()=>{const r=record(),ref={format:r.format,schemaVersion:1,kind:'reference',type:'motion',regions:['knees'],notes:123,data:r};assert.equal(engine().validatePoseObject(ref),false)});
test('unsafe creation metadata is rejected before persistence',()=>{const r=record();r.createdAt='<img src=x onerror="window.poisoned=true">';assert.equal(engine().validatePoseObject(r),false)});
function captureEngine(){const saved=[],state={recording:true,recordingStart:1000,recordingSamples:[],lastGapAt:0,inferenceTimes:[],workerReady:true,countdown:false};const c={state,performance:{now:()=>1000},validSamples:r=>r.samples.filter(s=>s.landmarks),drawLivePose:()=>{},readinessFrom:()=>({key:'fullBody',tone:'good'}),updateCaptureGuidance:()=>{},tr:k=>k,fmtTime:String,$:()=>({}),finishRecording:()=>{saved.push(true);state.recording=false}};vm.createContext(c);vm.runInContext(fn('handlePoseResult')+';this.capture=handlePoseResult',c);return{state,capture:c.capture,saved}}
test('capture preserves even a short lost-detection interval',()=>{const e=captureEngine();for(const [timestamp,landmarks]of [[1080,sample(0).landmarks],[1160,null],[1240,sample(0).landmarks]])e.capture({timestamp,landmarks});assert.equal(e.state.recordingSamples.length,3);assert.equal(e.state.recordingSamples[1].landmarks,null)});
test('capture cutoff cannot generate an unimportable five-minute recording',()=>{const e=captureEngine();e.capture({timestamp:301100,landmarks:sample(0).landmarks});assert.ok(e.state.recordingSamples.every(s=>s.t<=300000));assert.equal(e.saved.length,1)});
